import { Navbar } from '@/components/Navbar'
import { Outfit } from 'next/font/google'
import './globals.css'

const outfit = Outfit({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`bg-blue-500 ${outfit.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
